export type Team = {
  id: number;
  abbreviation: string;
  internal_abbreviation?: string;
  provider_id?: string | null;
  sport: string;
  league: "NFL" | "NBA" | "UFC";
  city: string;
  name: string;
  conference: string;
  division: string;
  logo_url: string;
  official_url: string;
};
export type Source = {
  id: number;
  provider_name: string;
  source_name: string;
  url: string;
  live_url: string | null;
  access_type: string;
  source_type: string;
  is_official: boolean;
  is_free: boolean;
  region: string;
  notes: string;
  status: string;
  last_checked: string | null;
  game_status?: string;
  user_has_subscription?: boolean;
  user_has_free_trial?: boolean;
};
export type Subscription = {
  id: number;
  provider_name: string;
  source_name: string;
  has_subscription: boolean;
  has_free_trial: boolean;
  notes: string;
  updated_at: string | null;
};
export type MyLink = {
  id: number;
  game_id: number | null;
  event_id?: number | null;
  url: string;
  source_name: string;
  notes: string;
  priority: number;
  enabled: boolean;
  shared_with_household: boolean;
  status: "ONLINE" | "OFFLINE" | "REDIRECT" | "UNKNOWN" | "WARNING" | "BLOCKED";
  playback_type: "DIRECT_MEDIA" | "EXTERNAL_PAGE" | "OFFICIAL_EMBED" | "BLOCKED";
  trust_state: "VERIFIED" | "UNVERIFIED" | "WARNING" | "BLOCKED";
  final_url: string | null;
  final_destination_domain: string | null;
  last_checked: string | null;
  last_successful_check: string | null;
  last_failure: string | null;
  successful_check_count: number;
  failure_count: number;
  average_response_time: number;
  redirect_count: number;
  last_opened_at: string | null;
  reliability_score: number;
  is_best?: boolean;
};
export type ProviderAccount = {
  provider: string;
  name: string;
  status: string;
  official_url: string;
  supports_casting: boolean;
  supports_embedded_playback: boolean;
};
export type Game = {
  id: number;
  season: number;
  week: number;
  season_type: "PRESEASON" | "REGULAR" | "POSTSEASON";
  sport: string;
  league: "NFL" | "NBA" | "UFC";
  kickoff_time: string | null;
  status: string;
  venue: string;
  broadcast_network: string | null;
  away_score: number | null;
  home_score: number | null;
  away_record: string | null;
  home_record: string | null;
  away_team: Team;
  home_team: Team;
  sources: Source[];
  my_links: MyLink[];
  development_data: boolean;
};
export type Preferences = {
  timezone: string;
  autoRefresh: boolean;
  showPaid: boolean;
  showFree: boolean;
  showAudio: boolean;
  league: "ALL" | "NFL" | "NBA" | "UFC";
};
export type NewsStory = {
  id: string;
  sport: string;
  league: "NFL" | "NBA" | "UFC";
  headline: string;
  description: string | null;
  source_name: string;
  source_url: string;
  image_url: string | null;
  published_at: string;
  updated_at: string | null;
  related_team_ids: string[];
  related_fighter_ids: string[];
  related_game_event_id: string | null;
  provider_id: string;
};
export type RecapParticipant = {
  id: number;
  name: string;
  abbreviation: string | null;
  score: number | null;
  record: string | null;
  headshot_url: string | null;
};
export type RecapNextEvent = {
  participant_id: number | null;
  label: string;
  event_id: number;
  event_time: string | null;
  route: string;
};
export type RecapBout = {
  id: number;
  card_section: string;
  weight_class: string | null;
  winner: RecapParticipant | null;
  loser: RecapParticipant | null;
  result_method: string | null;
  result_round: number | null;
  finish_time: string | null;
};
export type Recap = {
  id: string;
  sport: string;
  league: "NFL" | "NBA" | "UFC";
  event_id: number;
  status: "FINAL";
  completed_at: string | null;
  event_time: string | null;
  title: string;
  final_score: string | null;
  winner: RecapParticipant | null;
  loser: RecapParticipant | null;
  summary_facts: string[];
  top_performers: Array<Record<string, unknown>>;
  notable_stats: Array<Record<string, unknown>>;
  venue: string | null;
  broadcast_network: string | null;
  source_name: string;
  source_provider: string;
  teams: RecapParticipant[];
  bouts: RecapBout[];
  next_related: RecapNextEvent[];
};
export type StandingTeam = Team & {
  wins: number;
  losses: number;
  ties: number;
  win_percentage: string;
  division_record: string;
  conference_record: string;
  points_for: number;
  points_against: number;
  streak: string;
  playoff_rank: number | null;
  division_leader: boolean;
  conference_leader?: boolean;
  games_back?: string;
};
export type Standings = {
  league: "NFL" | "NBA";
  season: number;
  conferences: Array<{
    name: string;
    divisions: Array<{ name: string; teams: StandingTeam[] }>;
  }>;
};

export type NbaPlayer = {
  id: number;
  external_id: string;
  provider_id: string;
  league: string;
  team_id: number | null;
  full_name: string;
  first_name: string;
  last_name: string;
  display_name: string;
  short_name: string;
  jersey: string;
  position: string;
  position_name: string;
  position_abbreviation: string;
  height: string;
  weight: string;
  age: number | null;
  date_of_birth: string;
  birth_place: string;
  college: string;
  headshot_url: string;
  status: string;
  experience_years: number;
  draft_year: number | null;
  draft_round: number | null;
  draft_pick: number | null;
  career_stats: Record<string, { value: number | string; display: string }>;
  game_log: Array<{
    date: string;
    opponent: string;
    home_away: string;
    result: string;
    points: number | null;
    rebounds: number | null;
    assists: number | null;
    minutes: number | null;
    fg_made: number | null;
    fg_attempted: number | null;
    fg_pct: number | null;
    ft_made: number | null;
    ft_attempted: number | null;
    ft_pct: number | null;
    three_made: number | null;
    three_attempted: number | null;
    three_pct: number | null;
  }>;
  splits: Record<string, Array<{ name: string; value: number | string; display: string }>>;
  awards: Array<{ name: string; type: string; year: string; description: string }>;
};
